"""add installments, claim documents, claim history

Revision ID: 1a423cde46cc
Revises: 4df969a28de4
Create Date: 2026-08-01 15:09:22.920910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a423cde46cc'
down_revision: Union[str, Sequence[str], None] = '4df969a28de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_name', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_history_id'), 'claim_history', ['id'], unique=False)
    op.add_column('claims', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'claims', 'documents', ['document_id'], ['id'])
    op.add_column('insurance_plans', sa.Column('installments', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_plans', 'installments')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'document_id')
    op.drop_index(op.f('ix_claim_history_id'), table_name='claim_history')
    op.drop_table('claim_history')
    # ### end Alembic commands ###
