"""link customer to user, add plan_id to policy

Revision ID: 4df969a28de4
Revises: fd1a4e81641f
Create Date: 2026-07-28 17:56:20.858745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df969a28de4'
down_revision: Union[str, Sequence[str], None] = 'fd1a4e81641f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
