"""add otp fields and id proof to policies

Revision ID: 5fb2b43d1a0e
Revises: 164ec63d001e
Create Date: 2026-08-02 16:47:33.193211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb2b43d1a0e'
down_revision: Union[str, Sequence[str], None] = '164ec63d001e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('id_proof_type', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('id_proof_number', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('document_id', sa.Integer(), nullable=True))
    op.add_column('policies', sa.Column('installments_selected', sa.Integer(), nullable=True))
    op.add_column('policies', sa.Column('otp_code', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('otp_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('policies', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'policies', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_column('policies', 'otp_expires_at')
    op.drop_column('policies', 'otp_generated_at')
    op.drop_column('policies', 'otp_code')
    op.drop_column('policies', 'installments_selected')
    op.drop_column('policies', 'document_id')
    op.drop_column('policies', 'id_proof_number')
    op.drop_column('policies', 'id_proof_type')
    # ### end Alembic commands ###
