"""add insurance plans and link customer to user

Revision ID: fd1a4e81641f
Revises: 5f8bbce9ffe8
Create Date: 2026-07-28 17:48:16.875294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1a4e81641f'
down_revision: Union[str, Sequence[str], None] = '5f8bbce9ffe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('coverage_amount', sa.Float(), nullable=False),
    sa.Column('base_premium', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plans_id'), 'insurance_plans', ['id'], unique=False)
    op.add_column('customers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'customers', ['user_id'])
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'])
    op.add_column('policies', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'policies', 'insurance_plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_column('policies', 'plan_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'user_id')
    op.drop_index(op.f('ix_insurance_plans_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    # ### end Alembic commands ###
